global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'development'
    project: 'voice-ai-platform'

scrape_configs:
  - job_name: 'voice-ai-api'
    static_configs:
      - targets: ['api:3000']
    metrics_path: '/monitoring/metrics'
    scrape_interval: 10s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

# Alert rules
rule_files:
  - 'alerts.yml'

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ['alertmanager:9093']
