apiVersion: apps/v1
kind: Deployment
metadata:
  name: voice-ai-api
  namespace: voice-ai
  labels:
    app: voice-ai-api
    version: v1
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: voice-ai-api
  template:
    metadata:
      labels:
        app: voice-ai-api
        version: v1
    spec:
      containers:
      - name: api
        image: your-registry/voice-ai-api:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        - name: websocket
          containerPort: 8080
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: voice-ai-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: voice-ai-secrets
              key: redis-url
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: voice-ai-secrets
              key: openai-api-key
        - name: DEEPGRAM_API_KEY
          valueFrom:
            secretKeyRef:
              name: voice-ai-secrets
              key: deepgram-api-key
        - name: ELEVENLABS_API_KEY
          valueFrom:
            secretKeyRef:
              name: voice-ai-secrets
              key: elevenlabs-api-key
              optional: true
        - name: TWILIO_ACCOUNT_SID
          valueFrom:
            secretKeyRef:
              name: voice-ai-secrets
              key: twilio-account-sid
              optional: true
        - name: TWILIO_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: voice-ai-secrets
              key: twilio-auth-token
              optional: true
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: voice-ai-secrets
              key: jwt-secret
        - name: API_KEY_SECRET
          valueFrom:
            secretKeyRef:
              name: voice-ai-secrets
              key: api-key-secret
        - name: BASE_URL
          value: "https://api.yourdomain.com"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /monitoring/health/live
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /monitoring/health/ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: voice-ai-api
  namespace: voice-ai
  labels:
    app: voice-ai-api
spec:
  type: ClusterIP
  selector:
    app: voice-ai-api
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  - name: websocket
    port: 8080
    targetPort: 8080
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
---
apiVersion: v1
kind: Service
metadata:
  name: voice-ai-api-headless
  namespace: voice-ai
  labels:
    app: voice-ai-api
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: voice-ai-api
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  - name: websocket
    port: 8080
    targetPort: 8080
